### PR TITLE
Breakout reorg

### PR DESCRIPTION
**Pull request by alcantarar**
No time for 3 breakouts so condensed into 2. 

Changes made so far: 
- Breakout_1.md
- Breakout_2.md
- Reviewer_comments.md

### CODE REVIEW

**Comment by alcantarar** [comment]
working on matlab scripts now.

**Comment by alcantarar** [comment]
@GBruening I didn't go after the beta test feedback, just condensed things down to two breakouts, changing the markdowns and matlab scripts.

**Comment by alcantarar** [comment]
Made all the changes I had in my physical notes from beta test. Expect a tiny merge conflict when merging #21 because that also includes changes to readme contributor list.

**Comment by steve-kasica** [comment]
I've been merging changes into my local python-scripts branch. Merging it back to master will be easy because I've already merged changes from other branches.

**Pull request merged**
